---
title: "274hw2"
output: pdf_document
date: "2022-10-10"
---

```{r}
polyroot(c(1,-2/3,-1/3))

polyroot(c(1, 2,-8))
```
```{r}
#5.3
ma <- function(n, mu, theta, sd) {
  q <- length(theta)
  x <- numeric(n)
  eps <- rnorm(n, 0, sd)

  for(i in seq(q + 1, n)) {
    value <- mu + eps[i]
    for(j in seq_len(q)) {
      value <- value + theta[j] * eps[i - j]
    }
    x[i] <- value
  }
  x
}
set.seed(250)
t <- c(2,-8)
x_300 <- ma(300,0,t,1)
acf(x_300)
acf(x_300, lag=2, plot=FALSE)
x_1000 <- ma(1000,0,t,1)
acf(x_1000)
acf(x_1000, lag=2, plot=FALSE)
#it is getting closer to what we calculated
```
```{r}
#G2
AR <-function(n, mu, phi, sd){
  x <- numeric(n)
  p <- length(phi)
  eps <- rnorm(n, 0, sd)
  x[1] <- eps[1]
  if(p > 1){
  for(i in range(2,p)){
    val <- eps[i] + mu
    for(j in range(i-1)){
      val <- val + x[i-j] * phi[j]
    }
    x[i] <- val
  }
  }
  for(t in seq(p+1, n)){
    value <- eps[t]
    for(ph in seq_len(p)){
      value <- value + x[t-ph]*phi[ph]

    }
    
    x[t] <- value
  }
  x
}
set.seed(250)
phi_1 <- c(0.5, 0.4)#this is AR(2) model
ar1 <- AR(1000, 0, phi_1, 1)
acf(ar1)
phi_2 <- c(-0.5, 0.4)#another AR(2) model
ar2 <- AR(1000, 0, phi_2, 1)
acf(ar2)

```



